framework: jest
blocklist:
  - "./src/calculatorWithSuite.test.js##Test Language code_Expanded name to check for test suite_expand"
preRun:
  command:
    - npm ci          
postMerge:
  pattern: 
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
preMerge:
  pattern:
    - "./src/*.test.js"
  env:
    GLOAR_VARIABLE: es-ES
    ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
    INTVALUE: ${{ secrets.Int_value }}
postRun:
  command:
    - node --version
nodeVersion: 14.17.2
version: 1.7
